api:
  key: 069846F4A00F4245997FB66477B80BF9
appearance:
  defaultLanguage: en
feature: {}
gcodeViewer: {}
plugins:
  cura:
    cura_engine: /home/pi/CuraEngine/build/CuraEngine
  discovery:
    upnpUuid: 8c8ea64b-1dae-4c00-bb2f-276799939b7d
  softwareupdate:
    _config_version: 4
    checks:
      octoprint:
        checkout_folder: null
  touchui:
    hasCustom: false
    refreshCSS: false
    requireNewCSS: false
    whatsNew: false
printerParameters: {}
printerProfiles:
  defaultProfile:
    axes:
      e:
        inverted: false
        speed: 300
      x:
        inverted: true
        speed: 30000
      y:
        inverted: true
        speed: 30000
      z:
        inverted: true
        speed: 600
    color: default
    extruder:
      count: 1
      nozzleDiameter: 0.4
      offsets:
      - - 0.0
        - 0.0
    heatedBed: true
    id: _default
    model: Generic RepRap Printer
    name: Default
    volume:
      depth: 215.0
      formFactor: rectangular
      height: 193.0
      origin: lowerleft
      width: 215.0
serial:
  port: AUTO
  timeout: {}
server:
  commands: {}
  host: 127.0.0.1
  secretKey: OaoPfPPK5VZJszI1K9OnBaWjx96xoqVX
system:
  actions:
  - action: shutdown
    command: sudo shutdown -h now
    confirm: You are about to shutdown the system.
    name: Shutdown
  - action: reboot
    command: sudo shutdown -r now
    confirm: You are about to reboot the system
    name: Reboot
temperature: {}
webcam:
  ffmpeg: /usr/bin/avconv
  snapshot: http://127.0.0.1:8080/?action=snapshot
  stream: http://172.24.1.1:8080/?action=stream
  timelapse:
    fps: 25
    options:
      interval: 10
    postRoll: 0
    type: timed
